apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 8
    ssh:
      publicKeyName: sg
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 8
    ssh: 
      publicKeyName: sg